<?php
declare(strict_types=1);

/**
 * Set this to your tenant's Zscaler cloud domain:
 *   Examples: 'zscaler.net', 'zscloud.net', 'zscalerone.net', 'zscalertwo.net', 'zscalerthree.net'
 * If you prefer, set an env var ZSCALER_CLOUD and it'll use that instead.
 */
$zscalerCloud = getenv('ZSCALER_CLOUD') ?: 'zscaler.net';

/* ---- Read incoming params (all optional) ---- */
$targetUrl   = isset($_GET['url']) ? rawurldecode((string)$_GET['url']) : ''; // decode to avoid double-encoding on form submit
$referer     = $_GET['referer']     ?? '';
$reason      = $_GET['reason']      ?? '';
$reason_code = $_GET['reasoncode']  ?? '';
$timebound   = $_GET['timebound']   ?? '';
$actionTaken = $_GET['action']      ?? '';
$kind        = $_GET['kind']        ?? '';
$rule        = $_GET['rule']        ?? '';
$cat         = $_GET['cat']         ?? '';
$user        = $_GET['user']        ?? '';
$lang        = $_GET['lang']        ?? '';
$rid         = $_GET['zsq']         ?? ''; // IMPORTANT: send back exactly as received (do NOT strip 'zsq')

/* ---- Helpers ---- */
$e = fn($s) => htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8');
$formAction = "https://gateway.$zscalerCloud:443/_sm_ctn";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Access Restricted – AI Services</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #242424; color: #f0f0f0; margin: 0; padding: 20px; }
        .logo img { display: block; margin: 0 auto 16px; max-width: 360px; width: 100%; height: auto; }
        .container { max-width: 700px; margin: 50px auto; background-color: #2b2b2b; padding: 20px; box-shadow: 0 0 15px rgba(0,0,0,.5); }
        h1 { color: #5bc0de; }
        p { font-size: 16px; }
        a { color: #ffcc00; text-decoration: none; } a:hover { text-decoration: underline; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin-top: 12px; }
        .note { color: #c8c8c8; font-size: 13px; }
        .btn { display: inline-block; text-align: center; padding: 12px 16px; border-radius: 8px; font-weight: 700; background: #5bc0de; color: #1a1a1a; border: 0; cursor: pointer; }
        .details { margin-top: 20px; background-color: #333333; padding: 10px; border: 1px solid #444444; }
        .details p { font-size: 14px; margin: 5px 0; }
        ul { padding-left: 20px; }
        form { margin-top: 16px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <img src="CCHBC_2D_Color_Horizontal.png" alt="Coca-Cola HBC logo">
        </div>
        <h1>Access Restricted – AI Services</h1>
        <p>You are attempting to access a public generative AI service. Please follow these guidelines to protect privacy, security, and compliance.</p>

        <h2>Responsible AI Use Guidelines</h2>
        <ul>
            <li><strong>Always Think Privacy & Cyber-Security:</strong> Public AI platforms are public spaces. <em>Never</em> provide confidential company data or sensitive information.</li>
            <li><strong>Always Check the Quality:</strong> Validate AI outputs before using them.</li>
            <li><strong>Always Think Compliance:</strong> Inputs may be reused by the platform; share responsibly.</li>
            <li><strong>Always Label the Source of Data:</strong> Disclose AI assistance (e.g., “generated by use of ChatGPT”).</li>
            <li><strong>Always Use Responsibly:</strong> Keep human oversight in the loop.</li>
        </ul>

        <div class="useful-links">
            <strong>Suggestion:</strong> Prefer <strong>Corporate Copilot</strong>, our enterprise-approved AI assistant.
            <br><a class="btn" href="https://m365.cloud.microsoft.mcas.ms/chat/" target="_blank" rel="noopener">Open Corporate Copilot</a>
        </div>

        <!-- Zscaler Continue -->
        <form id="continue_action" method="GET" action="<?= $e($formAction) ?>">
            <input type="hidden" name="_sm_url" value="<?= $e($targetUrl) ?>">
            <input type="hidden" name="_sm_rid" value="<?= $e($rid) ?>">
            <input type="hidden" name="_sm_cat" value="<?= $e($cat) ?>">
            <button type="submit" class="btn" id="submitButton">Continue</button>
        </form>

        <div class="details">
            <h2>Support Information:</h2>
            <p><strong>Attempted URL:</strong> <?= $e($targetUrl) ?></p>
            <p><strong>Reason:</strong> <?= $e($reason) ?> (<?= $e($reason_code) ?>)</p>
            <p><strong>Action Taken:</strong> <?= $e($actionTaken) ?></p>
            <p><strong>Category:</strong> <?= $e($cat) ?></p>
            <p><strong>Rule:</strong> <?= $e($rule) ?></p>
            <p><strong>User:</strong> <?= $e($user) ?></p>
            <p><strong>Referer:</strong> <?= $e($referer) ?></p>
            <p><strong>Time-bound:</strong> <?= $e($timebound) ?></p>
        </div>
    </div>
</body>
</html>
