<?php
// --- Your original decoded values (for display only) ---
$url         = $_GET['url']        ?? '';
$referer     = $_GET['referer']    ?? '';
$reason      = $_GET['reason']     ?? '';
$reason_code = $_GET['reasoncode'] ?? '';
$timebound   = $_GET['timebound']  ?? '';
$action      = $_GET['action']     ?? '';
$kind        = $_GET['kind']       ?? '';
$rule        = $_GET['rule']       ?? '';
$cat         = $_GET['cat']        ?? '';
$user        = $_GET['user']       ?? '';
$lang        = $_GET['lang']       ?? '';

// --- NEW: grab the RAW (not decoded) values exactly as Zscaler sent them ---
$qs = $_SERVER['QUERY_STRING'] ?? '';
$rawParam = function(string $name) use ($qs): string {
    return preg_match('/(?:^|&)' . preg_quote($name, '/') . '=([^&]*)/i', $qs, $m) ? $m[1] : '';
};
$raw_url = $rawParam('url');   // e.g. https%3a%2f%2fchatgpt%2ecom%2f  (keep as-is!)
$raw_cat = $rawParam('cat');   // e.g. Generative+AI+and+ML+Applications
$raw_rid = $rawParam('zsq');   // e.g. MHjsVtF...zsq  (keep trailing "zsq")

// Build the exact continue URL (no re-encoding, no transforms)
$continueHref = "https://gateway.zscaler.net:443/_sm_ctn?_sm_url={$raw_url}&_sm_rid={$raw_rid}&_sm_cat={$raw_cat}";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Access Restricted – AI Services</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #242424;
            color: #f0f0f0;
            margin: 0;
            padding: 20px;
        }
        .logo img { 
            display: block; 
            margin: 0 auto 16px; 
            max-width: 360px; 
            width: 100%; 
            height: auto; 
        }        
        .container {
            max-width: 700px;
            margin: 50px auto;
            background-color: #2b2b2b;
            padding: 20px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.5);
        }
        h1 { color: #5bc0de; }
        p { font-size: 16px; }
        a { color: #ffcc00; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin-top: 12px; }
        .note { color: #c8c8c8; font-size: 13px; }
        .btn {
            display: inline-block; text-align: center; padding: 12px 16px; border-radius: 8px; font-weight: 700;
            background: #5bc0de; color: #1a1a1a; border: 0; cursor: pointer;
        }
        .details {
            margin-top: 20px; background-color: #333333;
            padding: 10px; border: 1px solid #444444;
        }
        .details p { font-size: 14px; margin: 5px 0; }
        ul { padding-left: 20px; }
        .actions { margin-top: 16px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <img src="CCHBC_2D_Color_Horizontal.png" alt="Coca-Cola HBC logo">
        </div>
        <h1>Access Restricted – AI Services</h1>
        <p>You are attempting to access a public generative AI service. Please follow these guidelines to protect privacy, security, and compliance.</p>

        <h2>Responsible AI Use Guidelines</h2>
        <ul>
            <li><strong>Always Think Privacy & Cyber-Security:</strong> Public AI platforms are public spaces. <em>Never</em> provide confidential company data or sensitive information.</li>
            <li><strong>Always Check the Quality:</strong> AI outputs can be incomplete or incorrect. Validate all results before using them.</li>
            <li><strong>Always Think Compliance:</strong> Generative AI platforms learn from user inputs. Share responsibly.</li>
            <li><strong>Always Label the Source of Data:</strong> If AI assisted your work, disclose it (e.g., “generated by use of ChatGPT”).</li>
            <li><strong>Always Use Responsibly:</strong> Keep human oversight in the loop.</li>
        </ul>

        <div class="useful-links">
            <strong>Suggestion:</strong> Whenever possible, rely on <strong>Corporate Copilot</strong>, our enterprise-approved AI assistant, instead of public AI services.
            <br><a class="btn" href="https://m365.cloud.microsoft.mcas.ms/chat/" target="_blank" rel="noopener">Open Corporate Copilot</a>
        </div>

        <!-- Continue: send bytes back EXACTLY as received (no form, no re-encoding) -->
        <div class="actions">
            <a id="submitButton" class="btn" href="<?= htmlspecialchars($continueHref, ENT_QUOTES, 'UTF-8') ?>">Continue</a>
        </div>

        <div class="details">
            <h2>Support Information:</h2>
            <p><strong>Attempted URL:</strong> <?= htmlspecialchars($url, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>Reason:</strong> <?= htmlspecialchars($reason, ENT_QUOTES, 'UTF-8') ?> (<?= htmlspecialchars($reason_code, ENT_QUOTES, 'UTF-8') ?>)</p>
            <p><strong>Action Taken:</strong> <?= htmlspecialchars($action, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>Category:</strong> <?= htmlspecialchars($cat, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>Rule:</strong> <?= htmlspecialchars($rule, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>User:</strong> <?= htmlspecialchars($user, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>Referer:</strong> <?= htmlspecialchars($referer, ENT_QUOTES, 'UTF-8') ?></p>
            <p><strong>Time-bound:</strong> <?= htmlspecialchars($timebound, ENT_QUOTES, 'UTF-8') ?></p>
        </div>

    </div>
</body>
</html>
